; BACKGROUND.Z80
;
; Map Source File.
;
; Info:
;   Section       : 9800
;   Bank          : 0
;   Map size      : 20 x 20
;   Tile set      : C:\Fischordner\Assembler\GB\Astro Attacc\Tileset.gbr
;   Plane count   : 0.5 plane (4 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 0
;   Split data    : No
;
; This file was generated by GBMB v1.8

BackgroundWidth  EQU 20
BackgroundHeight EQU 20
BackgroundBank   EQU 0

 SECTION "TILES", ROM0

Background::
DB $02,$02,$02,$02,$02,$02,$02,$02,$02
DB $02,$13,$13,$13,$13,$13,$13,$13,$13
DB $13,$13,$02,$02,$02,$02,$02,$02,$02
DB $02,$02,$02,$13,$13,$13,$13,$13,$13
DB $13,$13,$13,$13,$02,$02,$02,$02,$02
DB $02,$02,$02,$02,$02,$13,$13,$13,$13
DB $13,$13,$13,$13,$13,$13,$02,$02,$02
DB $02,$02,$02,$02,$02,$02,$02,$13,$13
DB $13,$13,$13,$13,$13,$13,$13,$13,$02
DB $02,$02,$02,$02,$02,$02,$02,$02,$02
DB $13,$13,$13,$13,$13,$13,$13,$13,$13
DB $13,$02

; End of BACKGROUND.Z80
